#! /bin/sh
# /etc/init.d/orbited
### BEGIN INIT INFO
# Provides:          orbited
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop Orbited
# Description:       Start or stop Orbited comet server
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting orbited"
    exec orbited --config=/etc/orbited.cfg &
    ;;
  stop)
    echo "Stopping orbited"
    killall orbited
    ;;
  *)
    echo "Usage: /etc/init.d/orbited {start|stop}"
    exit 1
    ;;
esac

exit 0